//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.31 at 02:23:04 PM MSK 
//


package almyal.ru.hospital.soap;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="timeslotInfo" type="{http://ru.almyal/hospital/soap}timeslotInfo"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "timeslotInfo"
})
@XmlRootElement(name = "generateTimeslotRequest")
public class GenerateTimeslotRequest {

    @XmlElement(required = true)
    protected TimeslotInfo timeslotInfo;

    /**
     * Gets the value of the timeslotInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TimeslotInfo }
     *     
     */
    public TimeslotInfo getTimeslotInfo() {
        return timeslotInfo;
    }

    /**
     * Sets the value of the timeslotInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeslotInfo }
     *     
     */
    public void setTimeslotInfo(TimeslotInfo value) {
        this.timeslotInfo = value;
    }

}
