//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.31 at 02:23:04 PM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://ru.almyal/hospital/soap", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package almyal.ru.hospital.soap;
